filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/cowrie-docker/logs/cowrie.json
    tags: ["cowrie"]

  - type: log
    enabled: true
    paths:
      - /var/log/honeypot/http.jsonl
    tags: ["http_honeypot"]
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    enabled: true
    paths:
      - /var/log/honeypot/ftp.jsonl
    tags: ["ftp_honeypot"]
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    enabled: true
    paths:
      - /var/log/honeypot/telnet.jsonl
    tags: ["telnet_honeypot"]
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["localhost:5044"]
